name: Send Weekly Email

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:      # Allow manual runs from GitHub

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Change to Monday-Curiosity-Script directory
        working-directory: ./Monday-Curiosity-Script
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python main.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
